# Generated by Django 6.0.4 on 2026-05-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_medication_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationhistory',
            name='recommended_medication',
            field=models.TextField(blank=True, null=True),
        ),
    ]
