# Generated by Django 6.0.4 on 2026-06-04 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_consultationhistory_predictions_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationhistory',
            name='confidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='Precaution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precautions', to='core.disease')),
            ],
        ),
    ]
